apiVersion: v1
data:
  config.yaml: |
    branch-protection:
      protect-tested-repos: true
    github:
      LinkURL: null
    in_repo_config:
      enabled:
        btukov/Jenkinsx_Demo: true
        btukov/Jx: true
        btukov/Jx_Pipeline: true
        btukov/Jx_Pipeline2: true
        btukov/Jx_Test: true
    plank: {}
    pod_namespace: jx
    prowjob_namespace: jx
    push_gateway:
      serve_metrics: true
    tide:
      context_options:
        from-branch-protection: true
        required-if-present-contexts: null
        skip-unknown-contexts: false
      merge_method:
        btukov/Jenkinsx_Demo: merge
        btukov/Jx: merge
        btukov/Jx_Pipeline: merge
        btukov/Jx_Pipeline2: merge
        btukov/Jx_Test: merge
      queries:
      - labels:
        - approved
        missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase
        repos:
        - btukov/Jx_Test
        - btukov/Jenkinsx_Demo
        - btukov/Jx_Pipeline
        - btukov/Jx_Pipeline2
        - btukov/Jx
      - labels:
        - updatebot
        missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase
        repos:
        - btukov/Jx_Test
        - btukov/Jenkinsx_Demo
        - btukov/Jx_Pipeline
        - btukov/Jx_Pipeline2
        - btukov/Jx
      target_url: http://lighthouse-jx.192.168.90.82.nip.io/merge/status
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: config
  namespace: jx
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
